### ISSUE TITLE
Unable to create a GL context

### ISSUE THREAD

**Issue by LewisAndSpark** [KenT2/pipresents-gtk#5]
Hi! I haven't tried this before (I'm new to raspberry pi and this type of stuff in general), but when I try to run any .mp4 (even from your example profiles) it opens a window that is black and says 'Unable to create a GL context'.

The terminal says 'Unable to acquire the address of the accessibility bus: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files. If you are attempting to run GTK without a11y support, GTK_A11Y should be set to 'none'.

and then it repeatedly outputs
Trying to snapshot trin94+MyRenderer 0x445f248 without a current allocation

and then if it runs long enough it closes with a new window with the message
MPVDriver load failed due to timeout load position is:-1

and the terminal says
System Error: MPVDrive/load_status_loop/167: load failed due to timeout load position is:-1
in dialog
error exit

I may also just be doing something basic wrong, or this might not be the right place to ask (apologies if it isn't).

**Comment by KenT2** [comment]
The first two messages are to be expected. The third 'MPVDriver load failed due to timeout load position is:-1'  in pp-gtk is indicative of the bug that causes PP-gtk to randomly crash when playing videos.

I have  recommended not using pp-gtk for videos until the bug is fixed. Please use pp-kms which unfortunately does not run on a Pi5

If you get the same error message on pp-kms it has in the past been caused by the video you are playing. Please contact me via pipresents.wordpress.com if that happens.

**Comment by LewisAndSpark** [comment]
kms worked perfectly, thank you

**Comment by LewisAndSpark** [comment]
kms worked perfectly, thank you
